# Heroku app name: si-devcon-alexa-1
sudo: required

language: java

services:
  - docker

before_install:
  - wget -qO- https://toolbelt.heroku.com/install.sh | sh

install:
  - gradle clean installDist

script:
  - heroku container:login
  - heroku container:push web -a si-devcon-alexa-1

deploy:
  provider: script
  script: heroku container:release web -a si-devcon-alexa-1
  on:
    branch: feature/team-1
