sudo: required

language: java

services:
  - docker

before_install:
  - wget -qO- https://toolbelt.heroku.com/install.sh | sh
  - echo "$HEROKU_PASSWORD" | docker login -u "$HEROKU_USERNAME" --password-stdin registry.heroku.com

install:
  - gradle installDist

script:
  - docker build -t si-devcon-alexa/heroku-test:latest .

deploy:
  provider: script
  script:
    #docker push si-devcon-alexa/heroku-test
    docker push registry.heroku.com/$HEROKU_APP/web;
    heroku container:release web --app $HEROKU_APP
  on:
    branch: feature/heroku
