server:
    type: simple
    applicationContextPath: /
    connector:
      type: http
      port: 8080

logging:
  level: INFO
  loggers:
    de.signaliduna.alexa: DEBUG
  appenders:
  - type: console

welcomeMessage: "Hello World!"