server:
    type: simple
    applicationContextPath: /
    connector:
      type: http
      port: 8080

logging:
  level: INFO
  loggers:
    de.signaliduna.alexa: DEBUG
  appenders:
  - type: console

database:
  driverClass: org.postgresql.Driver
  user: root
  password: root
  url: jdbc://example.com/database
  properties:
    charSet: UTF-8
  maxWaitForConnection: 1s
  validationQuery: "/* Health Check */ SELECT 1"
  minSize: 8
  maxSize: 32
  checkConnectionWhileIdle: false
  evictionInterval: 10s
  minIdleTime: 1 minute

httpClient:
  timeout: 500ms
  connectionTimeout: 500ms
  timeToLive: 1 hour
  cookiesEnabled: false
  maxConnections: 1024
  maxConnectionsPerRoute: 1024
  keepAlive: 0s

welcomeMessage: "Hello World!"